spring:
  application:
    name: AB-GATEWAY
  profiles:
    active: dev

---
spring:
  profiles: dev
  cloud:
    gateway:
      enabled: true
      routes:
      - id: dev_path_route
        uri: http://localhost:8082
        predicates:
        - Path=/dev/**
        filters:
        - PrefixPath=/hello
        - RewritePath=/dev(?<segment>/?.*), $\{segment}
      - id: test_path_route
        uri: http://localhost:8081
        predicates:
        - Path=/test/**
        filters:
        - RewritePath=/test(?<segment>/?.*), $\{segment}
        - PrefixPath=/hello
server:
  port: 8080
logging:
  level:
    org.springframework.cloud.gateway: TRACE